### ISSUE TITLE
Add LZ4 support

### ISSUE THREAD

**Issue by leandor** [wrye-bash/CBash#18]
(see original discussion here too -> wrye-bash/wrye-bash#338)

> The official lz4 is here: https://github.com/lz4/lz4

## TODO

 - [x] Incorporate dependence on LZ4 distribution
 - [ ] (1) Wrap simple functions from the library into python functions
 - [ ] Add python tests for simple functions in (1) 
 - [ ] (2) Next step is to wrap archive support functions
 - [ ] Add python tests for (2)
 - [ ] (3) Implement high level interface supporting python idioms and primitives based on the simple wrappers on (1) & (2)
 - [ ] Add tests for functionality on (3)
 - [ ] Documentation

**Comment by Utumno** [comment]
Thanks @leandor !

I really just need to decompress (save headers for SSE and bsas/b2as not sure what :P)

I guess this now depends on CBash 7 integration ?

EDIT: I first saw this and then the other (more noisy) issue - https://github.com/wrye-bash/wrye-bash/issues/338
