### ISSUE TITLE
Some pending issues on CBash pulled from WB issue tracker

### ISSUE THREAD

**Issue by leandor** [wrye-bash/CBash#2]
- Taken from wrye-bash/Wrye-Bash#264
  > Catch all issue to start investigating/splitting/fixing cint.py
- [ ] We are loading all fallout classes for naught - must be split into a package with a structure similar to the games one
- [ ] we must investigate if/how we can compile the dll for linux
- Taken from wrye-bash/Wrye-Bash#181
  - [ ] CBash patcher does not import names from csv files
